name: OMGorithm
description: algorithms, programming, and humans
meta_description: "OMGorithm"

aboutPage: true
encoding: UTF-8
markdown: redcarpet
highlighter: pygments

paginate: 7
baseurl: /
domain_name: 'http://omgorithm.com'
google_analytics: 'UA-49727693-5'
disqus_shortname: 'omgorithm'

# Details for the RSS feed generator
url:            'http://omgorithm.com'
author:         'OMGorithm'
creator:				'Pankesh Bamotra'
authorTwitter:  '_pbamotra_'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
